In [4]:
person = {
    "first": "Corey", 
    "last": "Schafer", 
    "email": "CoreyMSchafer@gmail.com"
}

In [5]:
people = {
    "first": ["Corey"], 
    "last": ["Schafer"], 
    "email": ["CoreyMSchafer@gmail.com"]
}

In [6]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [7]:
people['email']

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(people) # passing the dictionary that has the values as the list

In [10]:
df # represents in a way of rows and columns which we can visualise
# 0,1,2 -> unique value for our rows

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [11]:
df['email']
# the output of this doesn't really match to when we returned it from the dictionary
# when we printed from the dictionary -> output was in the form of a list
# here it is in form of a series

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [12]:
type(df['email']) # -> series object

pandas.Series

In [13]:
# series is still basically a list of data but it corresponds to a dataframe
# kindof like a 1D array
# it's basically rows of data

In [14]:
# dataframe -> rows and columns
# series -> rows of a single column

# hence dataframe is a container for multiple series objects

In [15]:
# dot notation
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [16]:
# accessing mutiple columns
# pass a list inside the brackets
df[['last', 'email']]
# here we get multiple columns as output hence it's not longer a series
# now it is just a filtered down dataframe

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [17]:
df.columns
# gives us all of the columns

Index(['first', 'last', 'email'], dtype='str')

In [18]:
# to get rows
# iloc -> access rows by integer notation
df.iloc[0] # first row

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [19]:
# can access multiple rows by passing a list of integers
df.iloc[[0,1]]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [20]:
# with these iloc and loc we can pass columns as well
# 1st argument - rows
# 2nd argument - columns
df.iloc[[0, 1] , 2] # email adresses of first 2 rows i.e. 2nd column of 0th and 1st row

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [21]:
# iloc -> we were searching by integer location
# loc -> will be searching by label
# labels for rows -> indexes

In [22]:
print(df)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [ ]:
df.loc[0] 
# get the row with label 0
# looks similar to iloc but will click when we actually use it in a dataset

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [ ]:
# can also pass in a list to specify mutiple rows
df.loc[[0,1]]
# output is a datafram now that we passed multiple rows

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [25]:
# in iloc we used inetegrs, in loc we can use labels
df.loc[[0,1], 'email']
# want email values only of the first 2 rows

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [ ]:
# if want email as well as last name, instead of passing just an email string, we can pass a list of strings
df.loc[[0,1], ['email', 'last']]
# the order in which we asked for is the order in which it is returned, we asked for email then last, it returned email then last

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe